version: '3'

services:
    api01:
        container_name: api01
        image: nmatsui/hello-world-api:0.1.1
        ports:
            - 3000:3000

    api02:
        container_name: api02
        image: nmatsui/hello-world-api:0.1.1
        ports:
            - 3001:3000
    
    api03:
        container_name: api03
        image: nmatsui/hello-world-api:0.1.1
        ports:
            - 3002:3000
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase